[package]
name = "frostmark"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13", default-features = false, features = ["wgpu", "tiny-skia", "advanced"] }
comrak = { version = "0.41", default-features = false }
html5ever = "0.27"
markup5ever_rcdom = "0.3"
